package scrap;

import java.util.Base64;

public class ValConst {
	
	public static void inizializza() {
		Constant.CHAT_ID_FANTALIVE = 425497266l;
		Constant.SPONTIT_KEY = new String(Base64.getDecoder().decode("M1hUSEhFNjdMSFI2RVFCS0kzNTlUMjBWOVY2NTI2SVYyUzdKSEMzUThEUEhJSDhWOU9DSDlJOTQ0UlBKWFdDMTA2SlpSQ05CQlFOMkVXUk1EOTBHWFM3RVczV1BYM08xRTFJUA=="));
		Constant.TOKEN_BOT_FANTALIVE = new String(Base64.getDecoder().decode("MTM2MzYyMDU3NTpBQUZMV0lMOUJNYjZMdnU1Z2lHLXhKd2JtN2h5VEtDSG5oWQ=="));
		Constant.SPONTIT_USERID = new String(Base64.getDecoder().decode("ZGFuaWVsZV9jYXJsdWNjaTY2OTU="));
		Constant.APPKEY_FG = new String(Base64.getDecoder().decode("NGFiMjdkNmRlMWU5MmM4MTBjNmQ0ZWZjODYwNzA2NWE3MzViOTE3Zg=="));
		Constant.AUTH_FS = new String(Base64.getDecoder().decode("RTQ5MTlGQTIyQjk5RDc3QjNDNzg0RjVFMjQxRjJCRTk1MTY4MTNCMkU1MUI0RUUzRUE1QTFGMzNGMkQyRUM2ODRDMDEwQUIzMTFCNThCQjhCNTE3OEE4MDBBRTBDRjEyQUZGNUFGODNDMzdGOTgzQjZCODE5OTdDRTA0NkRDNUFDMkQyRTEyNkQ3Q0JGRDQxRjcyRDYxQkM5NEE5QTI1RTc5Nzg3RThGRkZCMDU5Qzg5ODVBNzIwOTY0ODA0QjY1NDVGNTI1MzI0QzI3OTYxMDU0RUVBNDlEQzhCQkFBMjk2MzE5MEUzRQ=="));
	}
	
	


}
