package fantalive.util;

import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;

public class Constant {
	public static Integer GIORNATA;
	public static Long CHAT_ID_FANTALIVE;
	public static String SPONTIT_KEY;
	public static String TOKEN_BOT_FANTALIVE;
	public static String SPONTIT_USERID;
	public static String APPKEY_FG;
	public static String AUTH_FS;
	public static boolean LIVE_FROM_FILE;
	public static boolean DISABILITA_NOTIFICA_TELEGRAM;
	public static ZonedDateTime KEEP_ALIVE_END;
	public static ZonedDateTime LAST_KEEP_ALIVE;
	public static int SCHEDULED_SNAP;
	public static  int NUM_SQUADRE_BE = 0;	
	/*-------------------------------------------------------------------------------------------*/
	public static DateTimeFormatter dateTimeFormatterIn = DateTimeFormatter.ofPattern("yyyyMMddHHmm").withZone(ZoneId.of("Europe/Rome"));
	public static DateTimeFormatter dateTimeFormatterOut = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss").withZone(ZoneId.of("Europe/Rome"));
	public final static String PARTITA_FINITA = "\u2B59";
	public final static String PARTITA_NON_FINITA  = "\u23F3";
	public final static String OK_VOTO = "\u2714";
	public final static String NO_VOTO_IN_CORSO = "\u2753";
	public final static String PALLONE = "\u26BD";
	public final static String SVEGLIA  = "\u23F0";
	public final static String NO_VOTO_FINITO  = "\u274E";
	public static final String RIGORE_PARATO = "\u26BF";
	public final static String NO_VOTO_DA_INIZIARE = "\uD83D\uDECB";
	public final static String SCHIERATO = "\uD83D\uDCAA";
	public final static String NON_SCHIERATO = "\uD83D\uDE4F";
	public final static String SEMAFORO = "\uD83D\uDEA6";
	public static final String IMBATTUTO = "\uD83E\uDD45";
	public static final String ASSIST = "\uD83C\uDF6C";	
	public static final String GOL = "\uD83E\uDD42";
	public static final String USCITO =  "\u2BA9";
	public static final String ENTRATO =  "\u2BA8";
	public static final String GOL_ANNULLATO = "\uD83D\uDC7D";
	public static final String INFORTUNIO = "\uD83D\uDE91";
	public static final String AMMONITO = "\uD83D\uDFE8";
	public static final String ESPULSO = "\uD83D\uDFE5";
	public static final String GOL_SUBITO =  "\uD83C\uDF50";
	public static final String RIGORE_SBAGLIATO =   "\uD83D\uDE40";  
	public static final String RIGORE_SEGNATO = "\uD83E\uDD4A";
	public static final String AUTOGOL = "\uD83D\uDCA9";	
	public static final String CIAO = "\uD83D\uDC4B";
	public static final String KEEP_ALIVE = "\uD83E\uDE7A";
	public static final String P = "\u24C5";	
	public static final String D = "\u24B9";	
	public static final String C = "\u24B8";	
	public static final String A = "\u24B6";
	public static final String T1 = "\u2460";
	public static final String T2 = "\u2461";
	public static final String T3 = "\u2462";
	public static final String T4 = "\u2463";
	public static final String T5 = "\u2464";
	public static final String T6 = "\u2465";
	public static final String T7 = "\u2466";
	public static final String T8 = "\u2467";
	public static final String T9 = "\u2468";
	public static final String T10 = "\u2469";
	public static final String T11 = "\u246A";
	public static final String R1 = "\u2776";
	public static final String R2 = "\u2777";
	public static final String R3 = "\u2778";
	public static final String R4 = "\u2779";
	public static final String R5 = "\u277A";
	public static final String R6 = "\u277B";
	public static final String R7 = "\u277C";
	public static final String R8 = "\u277D";
	public static final String R9 = "\u277E";
	public static final String R10 = "\u277F";
	public static final String R11 = "\u24EB";
	public static final String R12 = "\u24EC";
	public static final String R13 = "\u24ED";
	public static final String R14 = "\u24EE";
	public static final String R15 = "\u24EF";
	public static final String R16 = "\u24FA";
	public static final String R17 = "\u24FB";
	public static final String R18 = "\u24FC";
	public static final String R19 = "\u24FD";
	public static final String R20 = "\u24FE";
	
	
	public static ZonedDateTime LAST_REFRESH;
}
